package analysis

import (
	"os"
	"path/filepath"
	"testing"
)

func TestAnalyzeUsesSharedExclusionsAndGocyclo(t *testing.T) {
	root := t.TempDir()
	write(t, root, "main.go", "package main\n\nvar top = func(x bool) { if x {} }\n\n//gocyclo:ignore\nfunc ignored(x bool) { if x {} }\n")
	write(t, root, "main_test.go", "package main\nfunc test() {}\n")
	write(t, root, "generated.go", "// Code generated by test. DO NOT EDIT.\npackage main\nfunc generated() {}\n")
	write(t, root, "build/ignored.go", "package build\nfunc ignored() {}\n")

	tree, err := Analyze(Options{Root: root, ExcludeGenerated: true, ExcludeDirs: []string{"build"}})
	if err != nil {
		t.Fatal(err)
	}
	if tree.Functions != 1 || tree.Complexity != 2 {
		t.Fatalf("functions=%d complexity=%d, want 1 and 2", tree.Functions, tree.Complexity)
	}
	if len(tree.Children) != 1 || tree.Children[0].Name != "main.go" {
		t.Fatalf("children = %+v", tree.Children)
	}
}

func TestAnalyzeReturnsParseErrors(t *testing.T) {
	root := t.TempDir()
	write(t, root, "broken.go", "package broken\nfunc nope(\n")
	if _, err := Analyze(Options{Root: root}); err == nil {
		t.Fatal("Analyze returned nil error for invalid Go")
	}
}

func TestGoclocCountsMultilineStrings(t *testing.T) {
	root := t.TempDir()
	write(t, root, "main.go", "package main\nvar text = `line one\nline two\nline three`\n")
	tree, err := Analyze(Options{Root: root})
	if err != nil {
		t.Fatal(err)
	}
	if tree.Code != 4 {
		t.Fatalf("code = %d, want 4", tree.Code)
	}
}

func write(t *testing.T, root, name, content string) {
	t.Helper()
	path := filepath.Join(root, name)
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
}
