package comparison

import (
	"os"
	"os/exec"
	"path/filepath"
	"testing"
)

func TestAnalyzeWorkingTreeAgainstBase(t *testing.T) {
	root := t.TempDir()
	runGit(t, root, "init", "-b", "main")
	runGit(t, root, "config", "user.email", "test@example.com")
	runGit(t, root, "config", "user.name", "Test")
	write(t, root, "keep.go", "package sample\nfunc keep(x int) { println(x) }\n")
	write(t, root, "delete.go", "package sample\nfunc dead(x int) { if x > 0 {} }\n")
	write(t, root, "old.go", "package sample\nfunc moved() {}\n")
	runGit(t, root, "add", ".")
	runGit(t, root, "commit", "-m", "base")
	runGit(t, root, "switch", "-c", "feature")

	write(t, root, "keep.go", "package sample\nfunc keep(x int) { if x > 0 { println(x) } }\n")
	if err := os.Remove(filepath.Join(root, "delete.go")); err != nil {
		t.Fatal(err)
	}
	if err := os.Rename(filepath.Join(root, "old.go"), filepath.Join(root, "new-name.go")); err != nil {
		t.Fatal(err)
	}
	runGit(t, root, "add", "old.go", "new-name.go")
	write(t, root, "untracked.go", "package sample\nfunc added(x int) { if x > 0 {} }\n")

	result, err := Analyze(Options{Root: root, Base: "main", ExcludeGenerated: true})
	if err != nil {
		t.Fatal(err)
	}
	if result.ComplexityAdded != 3 || result.ComplexityRemoved != 2 {
		t.Fatalf("complexity +%d -%d, want +3 -2: %+v", result.ComplexityAdded, result.ComplexityRemoved, result.Files)
	}
	if len(result.Files) != 4 {
		t.Fatalf("files = %d, want 4: %+v", len(result.Files), result.Files)
	}
	assertFile(t, result, "keep.go", "modified", 1, 0)
	assertFile(t, result, "delete.go", "deleted", 0, 2)
	assertFile(t, result, "new-name.go", "renamed", 0, 0)
	assertFile(t, result, "untracked.go", "added", 2, 0)
}

func TestAnalyzeRejectsMissingBase(t *testing.T) {
	root := t.TempDir()
	runGit(t, root, "init", "-b", "main")
	runGit(t, root, "config", "user.email", "test@example.com")
	runGit(t, root, "config", "user.name", "Test")
	write(t, root, "main.go", "package main\n")
	runGit(t, root, "add", ".")
	runGit(t, root, "commit", "-m", "base")
	if _, err := Analyze(Options{Root: root, Base: "missing"}); err == nil {
		t.Fatal("Analyze returned nil error for missing base")
	}
}

func TestAnalyzeAppliesFiltersAndReportsParseWarnings(t *testing.T) {
	root := t.TempDir()
	initRepository(t, root)
	write(t, root, "space dir/file name.go", "package sample\nfunc valid() {}\n")
	write(t, root, "generated.go", "// Code generated by test. DO NOT EDIT.\npackage sample\nfunc generated() {}\n")
	write(t, root, "sample_test.go", "package sample\nfunc testOnly() {}\n")
	runGit(t, root, "add", ".")
	runGit(t, root, "commit", "-m", "base")
	runGit(t, root, "switch", "-c", "feature")
	write(t, root, "space dir/file name.go", "package sample\nfunc broken( {\n")
	write(t, root, "generated.go", "// Code generated by test. DO NOT EDIT.\npackage sample\nfunc generated() { if true {} }\n")
	write(t, root, "sample_test.go", "package sample\nfunc testOnly() { if true {} }\n")

	result, err := Analyze(Options{Root: root, Base: "main", ExcludeGenerated: true, ContinueOnError: true})
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Files) != 1 || result.Files[0].Path != "space dir/file name.go" || len(result.Warnings) != 1 {
		t.Fatalf("result = %+v", result)
	}
}

func TestAnalyzeEmptyDiff(t *testing.T) {
	root := t.TempDir()
	initRepository(t, root)
	write(t, root, "main.go", "package main\n")
	runGit(t, root, "add", ".")
	runGit(t, root, "commit", "-m", "base")
	result, err := Analyze(Options{Root: root, Base: "main"})
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Files) != 0 || result.ComplexityAdded != 0 {
		t.Fatalf("result = %+v", result)
	}
}

func assertFile(t *testing.T, result *Result, path, status string, added, removed int) {
	t.Helper()
	for _, file := range result.Files {
		if file.Path == path {
			if file.Status != status || file.ComplexityAdded != added || file.ComplexityRemoved != removed {
				t.Fatalf("%s = %+v", path, file)
			}
			return
		}
	}
	t.Fatalf("file %s not found: %+v", path, result.Files)
}

func write(t *testing.T, root, name, body string) {
	t.Helper()
	path := filepath.Join(root, name)
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
}

func runGit(t *testing.T, root string, args ...string) {
	t.Helper()
	command := exec.Command("git", append([]string{"-C", root}, args...)...)
	if output, err := command.CombinedOutput(); err != nil {
		t.Fatalf("git %v: %v\n%s", args, err, output)
	}
}

func initRepository(t *testing.T, root string) {
	t.Helper()
	runGit(t, root, "init", "-b", "main")
	runGit(t, root, "config", "user.email", "test@example.com")
	runGit(t, root, "config", "user.name", "Test")
}
